package com.example.backend.artwork;

public enum Categories {
	AI_ART, TWOD_DIGITAL_PAINTING, THREED_DIGITAL_PAINTING, GENERATIVE_ART, PIXEL_ART, FRACTAL_ART, ALGORITHMIC_ART,
	DIGITAL_PHOTOGRAPHY, VR_PAINTING, TWOD_COMPUTER_GRAPHICS, THREED_COMPUTER_GRAPHICS, PHOTOBASHING, PHOTO_PAINTING,
	DATA_MOSHING, DYNAMIC_PAINTING, DIGITAL_COLLAGE, RASTER_PAINTING, VECTOR_ART, INTEGRATED_ART, MIXED_MEDIA,
	COMPUTER_GENERATED_DIGITAL_PAINTING
}